// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payslip.API.Models;

namespace Payslip.API.Migrations
{
    [DbContext(typeof(PayslipDbContext))]
    [Migration("20210530080217_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payslip.API.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("FinancialYearEnd")
                        .HasColumnType("int");

                    b.Property<int>("FinancialYearStart")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TaxRateLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaxRateLevelId");

                    b.ToTable("TaxRates");
                });

            modelBuilder.Entity("Payslip.API.Models.TaxRateLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("TaxRateTypeInternal")
                        .HasColumnType("int");

                    b.Property<int>("TaxableIncomeLowerBound")
                        .HasColumnType("int");

                    b.Property<int?>("TaxableIncomeUpperBound")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxRateLevels");
                });

            modelBuilder.Entity("Payslip.API.Models.TaxRate", b =>
                {
                    b.HasOne("Payslip.API.Models.TaxRateLevel", "TaxRateLevel")
                        .WithMany()
                        .HasForeignKey("TaxRateLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaxRateLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
